/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_DDMeter
#define HEADER_DDMeter
/*
htop - BatteryMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.

This meter written by Ian P. Hands (iphands@gmail.com, ihands@redhat.com).
*/


#include "Meter.h"


extern int DDMeter_attributes[];

extern MeterClass DDMeter_class;

#endif
