/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_DDMeter
#define HEADER_DDMeter
/*
htop - DDMeter.c

This meter written by Pierre Manceron.
*/

#include "Meter.h"

extern int DDMeter_attributes[];

extern MeterClass DDMeter_class;

#endif
