/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Statsd
#define HEADER_Statsd
/* 
 * udpserver.c - A simple UDP echo server 
 * usage: udpserver <port>
 */

#define BUFSIZE 1024

int Statsd_run(void *portno);

void Statsd_init(int portno);

double Statsd_getMetric(const char* metricName);

#endif
