/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Statsd
#define HEADER_Statsd
/*
 * udpserver.c - A simple UDP echo server
 * usage: udpserver <port>
 */

#define BUFSIZE 1024

struct Hashtable_ *metrics;

typedef struct Metric {
  char *name;
  double currentVal;
  double maxVal;
} Metric;

unsigned long hash(unsigned char *str);

void *Statsd_run(void *portno);

void Statsd_init(int portno);

void Statsd_shutdown();

double Statsd_getMetric(const char* metricName);

#endif
